export function buildMM109Fields(summary: any): {
  applicantCompany: any;
  roadwayType: any;
  latitude: any;
  longitude: any;
  type: any;
  applicant: any;
  jobName: any;
  jobNumber: any;
  owner: any;
  commCompany: any;
  submissionProfileName: any;
  manifestType: any;
  environment: any;
  poleHeightFt: any;
  poleClass: any;
  poleLatitude: any;
  poleLongitude: any;
  midLatitude: any;
  midLongitude: any;
  fromPoleId: any;
  toPoleId: any;
  fromLatitude: any;
  fromLongitude: any;
  toLatitude: any;
  toLongitude: any;
  powerVoltage: any;
  powerHeight: any;
  spanLengthFt: any;
  midspanFt: any;
  targetGroundClearanceFt: any;
  computedGroundClearanceFt: any;
  targetSource: any;
  attachProposedFt: any;
  attachBasis: any;
  attachDetail: any;
  generatedAt: any;
};
export function buildCSXFields(summary: any): {
  applicantCompany: any;
  crossingType: any;
  latitude: any;
  longitude: any;
  type: any;
  applicant: any;
  jobName: any;
  jobNumber: any;
  owner: any;
  commCompany: any;
  submissionProfileName: any;
  manifestType: any;
  environment: any;
  poleHeightFt: any;
  poleClass: any;
  poleLatitude: any;
  poleLongitude: any;
  midLatitude: any;
  midLongitude: any;
  fromPoleId: any;
  toPoleId: any;
  fromLatitude: any;
  fromLongitude: any;
  toLatitude: any;
  toLongitude: any;
  powerVoltage: any;
  powerHeight: any;
  spanLengthFt: any;
  midspanFt: any;
  targetGroundClearanceFt: any;
  computedGroundClearanceFt: any;
  targetSource: any;
  attachProposedFt: any;
  attachBasis: any;
  attachDetail: any;
  generatedAt: any;
};
export function buildStateHighwayFields(
  summary: any,
  agencyLabel: any,
): {
  agency: any;
  roadwayType: any;
  latitude: any;
  longitude: any;
  type: any;
  applicant: any;
  jobName: any;
  jobNumber: any;
  owner: any;
  commCompany: any;
  submissionProfileName: any;
  manifestType: any;
  environment: any;
  poleHeightFt: any;
  poleClass: any;
  poleLatitude: any;
  poleLongitude: any;
  midLatitude: any;
  midLongitude: any;
  fromPoleId: any;
  toPoleId: any;
  fromLatitude: any;
  fromLongitude: any;
  toLatitude: any;
  toLongitude: any;
  powerVoltage: any;
  powerHeight: any;
  spanLengthFt: any;
  midspanFt: any;
  targetGroundClearanceFt: any;
  computedGroundClearanceFt: any;
  targetSource: any;
  attachProposedFt: any;
  attachBasis: any;
  attachDetail: any;
  generatedAt: any;
};
declare namespace _default {
  export { buildMM109Fields };
  export { buildCSXFields };
  export { buildStateHighwayFields };
}
export default _default;
