name: PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  verify:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit --fund=false --progress=false

      - name: Verify (lint, tests, build)
        run: npm run verify

      - name: Security audit (non-blocking)
        run: npm audit --omit=dev --audit-level=moderate || echo "audit reported issues (non-blocking)"

  coverage:
    name: Coverage
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-coverage
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit --fund=false --progress=false

      - name: Test with coverage
        run: npm run test:coverage

      - name: Upload coverage artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
          if-no-files-found: warn
