name: PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  verify:
    name: Verify (lint, test, build)
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-verify
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit --fund=false --progress=false

      - name: Lint (non-blocking)
        run: npm run lint || true

      - name: Test
        run: npm test -- --run

      - name: Build
        run: npm run build

      - name: Security audit (non-blocking)
        run: npm audit --omit=dev --audit-level=moderate || echo "audit reported issues (non-blocking)"

  coverage:
    name: Coverage
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-coverage
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit --fund=false --progress=false

      - name: Test (coverage)
        run: |
          if npm run | grep -q "test:coverage"; then
            npm run test:coverage
          else
            npm test -- --coverage
          fi

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
          if-no-files-found: ignore
